#stage 1

FROM node AS builder

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build
# stage 2
FROM node

WORKDIR /app/build

RUN npm install -g http-server

COPY --from=builder /app/build /app/build

CMD http-server
